### ISSUE TITLE
Unable to find files to extract

### ISSUE THREAD

**Issue by wpw** [Jayveer/Decima-Explorer#9]
Hi, I've successfully dumped the file list, but when I try to extract a file found within that list, I'm unable to get it to work.

Here's an example input: 
`DecimaExplorer.exe -extract "C:\Program Files (x86)\Steam\steamapps\common\Death Stranding\data" \ds\models\item\ludk_ludenskeyring\core\ludk_main_big\model\parts\mesh_main_lx`

Which results in this output:
```
Running Decima Explorer v1.5:
Visit https://github.com/Jayveer/Decima-Explorer for updates:

Failed to find file ╨¡»‼;☻
```

Note the weird filename - this changes every time the command is run, even when the args are the same. Am I formatting the extract options incorrectly or missing something else?

Edit: messed around more and realized that some of the issues may be with specific files being extracted/decrypted and not with the Decima-Explorer tool per se. The example of the Ludens keyring model (ds/models/item/ludk_ludenskeyring/core/*) I posted before fails for files descending from the /ludk_main_big/ directory. However, ones that are in /ludk_main_def/ or /ludk_main_hlo/ or /ludk_textures/ all extract/decrypt fine. Still unable to get full folder extraction to work, but doing it as single files seems less prone to errors.

Also after lots of trial and error, I found that I got more success putting the DecimaExplorer.exe into the /Death Stranding/data/ folder and running from there instead of putting it in the game's root and specifying the data location. Example command string that works: `DecimaExplorer.exe -e ./ ds/models/item/whatever_asset_to_be_extracted/asset_name`

Still have no idea what to do with the files after extraction, though, since the other tool for converting the .core files of the PS4 version doesn't run on my machine (out of memory exception).

**Comment by Jayveer** [comment]
Hi, thanks for raising the issue and making it detailed. I am guessing it is around characters in the path messing up the path so I'll need to handle that.

**Comment by Jayveer** [comment]
I have fixed the issue with  the string output containing rubbish in the latest release. I've also updated the readme examples to show that the game data paths will use forward slashes, as the game specifically uses these paths for the hash value I decided I'm reluctant to allow a backslash. I believe these two changes should be enough to close this issue.
